database:
  enabled: true
  url: jdbc:mysql://localhost:3306/minecraft?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  username: minecraft
  password: minecraft

client:
  namespace: "Xigua_common"
  system-name: "main"

pythonRPC-plugin-massage-name: "floodgate:netease"
debug: false
enable-ping: false

is-test-server: true

netease-shop:
  enable-java: false
  bedrock:
    shop-url: "http://gasproxy.mc.netease.com:60002"
    test-shop-url: "http://gasproxy.mc.netease.com:60001"
    game-id: ""
    game-key: ""
    test-game-key: ""
  java:
    shop-url: "http://gasproxy.mc.netease.com:60004"
    test-shop-url: "http://gasproxy.mc.netease.com:60003"
    game-id: ""
    game-key: ""
    test-game-key: ""